apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-core-configmap.yaml
  - postgres-core-secret.yaml
  - postgres-core-statefulset.yaml
  - postgres-core-service.yaml
  - postgres-vendas-configmap.yaml
  - postgres-vendas-secret.yaml
  - postgres-vendas-statefulset.yaml
  - postgres-vendas-service.yaml
