apiVersion: v1
kind: Service
metadata:
  name: postgres-vendas
  labels:
    app: postgres-vendas
spec:
  selector:
    app: postgres-vendas
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
