apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-vendas
  labels:
    app: postgres-vendas
spec:
  serviceName: postgres-vendas
  replicas: 1
  selector:
    matchLabels:
      app: postgres-vendas
  template:
    metadata:
      labels:
        app: postgres-vendas
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
              name: postgres
          envFrom:
            - configMapRef:
                name: postgres-vendas-config
            - secretRef:
                name: postgres-vendas-secret
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres", "-d", "veiculos_vendas_db"]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres", "-d", "veiculos_vendas_db"]
            initialDelaySeconds: 15
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
